### ISSUE TITLE
data.table vs tidyverse use. 

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#19]
I can see that the code is using a lot of data.table. We could think about translating some parts of the code and the Vignette to tidyverse. It would be more user-friendly but slower. Maybe the functions should be written in data.table but the Vignette in tidyverse?

 [https://www.waldrn.com/dplyr-vs-data-table/](url)

**Comment by schoolAccountMajaG** [comment]
For example here https://github.com/lhenneman/hyspdisp/blob/master/vignettes/hyads.Rmd#L44-L46 
data.table is 4 times quicker than dplyr/tidyverse... How do we prioritize... user experience or speed? (Assuming an average user is more familiar with dplyr)

**Comment by cchoirat** [comment]
There are some `dplyr` operations that can be run on data.table object.

Also, there are packages that may help: https://github.com/gdemin/maditr if
you decide to stick to data.table.

**Comment by lhenneman** [comment]
I think we should prioritize speed within the functions, since there's a lot of reading and writing that happens throughout. Re: changing the vignette, I'm happy either way. We'd have to make sure that the functions played nicely with data.frames as inputs (they may already, but we should check).

**Comment by cchoirat** [comment]
I'm a huge fan of data.table ;)

**Comment by schoolAccountMajaG** [comment]
Ok, I think we should stick to the data.table then!

**Comment by cchoirat** [comment]
i think it's possible to use pipes %>% and such with data.table.

**Comment by schoolAccountMajaG** [comment]
decided to use data.table
