### ISSUE TITLE
Tigris use for ZCTA shapefiles. 

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#20]
Maybe adding Tigris would make things easier for ZCTA shapefiles? Sometimes getting the right files can be confusing for a user who is new to it should there be any change on the website.

**Comment by schoolAccountMajaG** [comment]
https://github.com/lhenneman/hyspdisp/blob/master/vignettes/hyads.Rmd#L58-L78

**Comment by cchoirat** [comment]
What is the issue specifically about?

**Comment by schoolAccountMajaG** [comment]
Incorporate Tigris in the package?

**Comment by cchoirat** [comment]
The package or the files??

**Comment by cchoirat** [comment]
You mean the tigris package?

**Comment by schoolAccountMajaG** [comment]
Tigris package in hyspdisp for less advanced users. Inside hyspdisp functions.

**Comment by cchoirat** [comment]
Why for less advanced users?

**Comment by schoolAccountMajaG** [comment]
It just makes the data easily accessible.

**Comment by cchoirat** [comment]
I mean why not for everybody if it works and is easy?

**Comment by schoolAccountMajaG** [comment]
built vignette with data preprocessing explained instead in disperseR
