### ISSUE TITLE
give a list of packages to be loaded in the vignette. 

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#22]
It would be cool if all the libraries that are used/necessary were listed in the documentation + read in at the beg of the vignette

**Comment by cchoirat** [comment]
What do you mean by libraries?  R packages?  If so, it should be in the
DESCRIPTION function.  If not, should it be in the vignette or in a helper
function?

**Comment by schoolAccountMajaG** [comment]
Yes, R packages should be all listed in one place in the documentation. Also in the vignette for example like that:


We will be using the following packages: 

1. "hyspdisp"
2. "openxlsx"
3. "ncdf4"
4. "parallel"
5. "sf"
6. "viridis"
7. "scales"
8. "ggsn"
9. "SplitR"
10. "tidyverse"

The code below will check if you have the necessary packages installed and install them in case they are are not installed.

`
### If packages are not installed this code will install them
list.of.packages <- c("hyspdisp", "openxlsx", "ncdf4", "parallel", "sf", 
                      "viridis", "scales", "ggsn", "SplitR", "tidyverse")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages)
`


We load the required packages/libraries below.

`library(hyspdisp)
library(openxlsx)
library(ncdf4)
library(parallel)
library(sf)
library(viridis)
library(scales)
library(ggsn)
library(SplitR)
library(tidyverse)
`

**Comment by cchoirat** [comment]
You really want/should handle this at the R package level, see, e.g.,
http://r-pkgs.had.co.nz/description.html.

**Comment by schoolAccountMajaG** [comment]
handled at package level in disperseR
