### ISSUE TITLE
Functions have possibly too many arguments. 

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#24]
It is a bit confusing to understand all the arguments in the functions at first. Could we rewrite some things?

**Comment by schoolAccountMajaG** [comment]
https://github.com/lhenneman/hyspdisp/blob/master/vignettes/hyads.Rmd#L242-L251 here is an example example. What do you think?

I also got confused with [https://github.com/lhenneman/hyspdisp/blob/master/vignettes/hyads.Rmd#L219-L228](url) when trying to debug

**Comment by cchoirat** [comment]
Second link should be https://github.com/lhenneman/hyspdisp/blob/master/vignettes/hyads.Rmd#L219-L228

**Comment by schoolAccountMajaG** [comment]
Tried to reduce as much as possible but it was difficult. New functions and arguments implemented in disperseR
