### ISSUE TITLE
 Not all the functions have Rd. files. 

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#31]
I can install hyspdisp but when I want to read about the functions using ?name_of_function it shows no documentation. Need to figure out why

**Comment by schoolAccountMajaG** [comment]
Ok.. I figured it out.

**Comment by cchoirat** [comment]
Before closing, please document the part you figured out.

**Comment by schoolAccountMajaG** [comment]
Not all the functions have Rd. files.

**Comment by cchoirat** [comment]
you mean not all the functions?

and should they?

**Comment by schoolAccountMajaG** [comment]
Yes! I am sorry. I edited it. Yes, they should!

**Comment by cchoirat** [comment]
You can decide with @lhenneman which functions matter in the workflow, and document them carefully.  You don't have to export all the functions of the package: http://r-pkgs.had.co.nz/namespace.html.

Also a large part of the process can be automated (https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html):

> Roxygen2 dynamically inspects the objects that it’s documenting, so it can automatically add data that you’d otherwise have to write by hand.

**Comment by cchoirat** [comment]
By the way issue title is a little ambiguous: Not all the packages have Rd. files.
