### ISSUE TITLE
syntax package::function()?

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#33]
> "Imports: packages listed here must be present for your package to work. In fact, any time your package is installed, those packages will, if not already present, be installed on your computer (devtools::load_all() also checks that the packages are installed).

> Adding a package dependency here ensures that it’ll be installed. However, it does not mean that it will be attached along with your package (i.e., library(x)). **The best practice is to explicitly refer to external functions using the syntax package::function().** This makes it very easy to identify which functions live outside of your package. This is especially useful when you read your code in the future."

http://r-pkgs.had.co.nz/description.html

Should we implement package::function()? 

For example, we could do it here: https://github.com/lhenneman/hyspdisp/blob/master/R/hyspdisp_fac_model.R#L113 as create_disp_model comes from SplitR. 

What do you think @cchoirat?

**Comment by cchoirat** [comment]
yes, that's good practice

**Comment by schoolAccountMajaG** [comment]
implemented
