### ISSUE TITLE
package ‘SplitR’ is not available (for R version 3.6.0)

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#46]
@cchoirat What do you suggest doing?

I have updated my R version and now I cannot install a dependency.

**Comment by cchoirat** [comment]
what is the error message?

**Comment by schoolAccountMajaG** [comment]
Warning in install.packages : package ‘SplitR’ is not available (for R version 3.6.0)

Also: Remotes: lhenneman/SplitR in the description file does not help automatically.

**Comment by cchoirat** [comment]
are you installing from github?  from which repo?

**Comment by schoolAccountMajaG** [comment]
Impossible to install from CRAN because of this error. 

install_github("lhenneman/SplitR") installs it but this should be either automatic or very clearly specified somewhere, not only in the description file.

**Comment by cchoirat** [comment]
is splitr on CRAN then?

**Comment by schoolAccountMajaG** [comment]
It is not. My bad! sorry!
