### ISSUE TITLE
Remove data folders

### ISSUE THREAD

**Issue by cchoirat** [lhenneman/hyspdisp#55]
@garbulinskamaja are these folders/files needed?

![image](https://user-images.githubusercontent.com/4173925/61697701-18f51700-ad38-11e9-88df-79e45dd1af0e.png)

**Comment by schoolAccountMajaG** [comment]
nope, this is just a product of some test runs

**Comment by schoolAccountMajaG** [comment]
I will clean it up soon

**Comment by cchoirat** [comment]
then can you please remove them?  they shouldn't be on git

**Comment by schoolAccountMajaG** [comment]
deleted the branch. Work has been done in disperseR repo in my github, will be transformed to @lhenneman
